dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: infra-cicd-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.4
- name: jenkinsx-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: jenkinsx-demo-3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
